entero cantidadpersonas,ciclo,i

inicio

escriba("cuantas encuestas va a realizar")
lea cantidadpersonas

para ciclo<-i hasta cantidadpersonas haga
escriba("que le gusta hacer")
llamar nueva_linea
escriba("1.cine")
llamar nueva_linea
escriba("2.comer")
llamar nueva_linea
escriba("3.realizar deportes")
llamar nueva_linea
escriba("4.gym")
llamar nueva_linea
escriba("5.hablar")
llamar nueva_linea
escriba("6.cena romantica")
llamar nueva_linea

fin para 

fin